name: Deploy to Environment
description: 'Deploy repo to environment'
inputs:
  aws-account:
    description: 'AWS account to assume'
    required: true
  image-tag:
    description: 'Image tag to deploy'
    required: true
  tags:
    description: 'Accounting tag for the cloudformation stack'
    required: false
  sqs-config-file-path:
    description: 'SQS config file to store in SSM'
    default: ''
    required: false
  cf-template:
    description: 'Path to cloudformation template'
    required: true
  name:
    description: 'Name of the cloudformation stack'
    required: true
  ssm-path:
    description: 'Path to store SQS config in SSM'
    default: ''
    required: false
  repository:
    description: 'Docker ecr repo'
    required: true
  environment:
    description: 'The environment to deploy to'
    required: true
  cdn-bucket:
    description: 'Sync CDN with public folder'
    default: ''
    required: false
  set-asset-url:
    description: 'Set to a non-empty string to use the asset-url output from the sync-cdn step'
    default: ''
    required: false
  parameter-overrides:
    description: 'Cloudformation parameter overrides'
    default: ''
    required: false

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Assume CD/CI role for AWS account
      uses: bisnow/github-actions-assume-role-for-environment@main
      with:
        aws-account: ${{ inputs.aws-account }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Pull image
      shell: bash
      run: |
        docker pull --platform=linux/arm64 ${{ inputs.repository }}:${{ inputs.image-tag }}
    - name: Sync assets with CDN
      if: ${{ inputs.cdn-bucket != '' }}
      id: sync-cdn
      shell: bash
      run: |
        docker create --platform=linux/arm64 --name build-${{ github.run_id }} ${{ inputs.repository }}:${{ inputs.image-tag }}
        docker cp build-${{ github.run_id }}:/app/public ./s3-public-${{ github.run_id }}
        export CDN_PATH=$(cd s3-public-${{ github.run_id }} && basename $(find . -maxdepth 1 -type d -name "rc-[0-9]*"))
        echo "::set-output name=asset-url::https://${{ inputs.cdn-bucket }}/$CDN_PATH"
        aws s3 sync ./s3-public-${{ github.run_id }}/$CDN_PATH s3://${{ inputs.cdn-bucket }}/$CDN_PATH \
          --cache-control max-age=31536000 \
          --exclude "*.php" --exclude ".htaccess" --exclude ".gitignore" --exclude "*.txt" --exclude "*icon*" --exclude "vendor" --exclude "mix-manifest.json" \
          --follow-symlinks --delete
        docker rm build-${{ github.run_id }}
        rm -rf ./s3-public-${{ github.run_id }}
    - name: Tag image and push image
      shell: bash
      run: |
        docker buildx imagetools create -t ${{ inputs.repository }}:${{ inputs.environment }} ${{ inputs.repository }}:${{ inputs.image-tag }}
    - name: Check cloudformation template
      uses: stelligent/cfn_nag@master
      with:
        input_path: "{{ inputs.cf-template }}"
    - name: Write sqs config file to SSM
      uses: bisnow/github-actions-store-sqs-config-ssm@v1.2
      if: ${{ inputs.sqs-config-file-path != '' }}
      with:
        file-path: ${{ inputs.sqs-config-file-path }}
        base64: 'true'
        ssm-path: ${{ inputs.ssm-path }}
    - name: Prepare Parameter Overrides
      id: prepare-overrides
      shell: bash
      run: |
        overrides="ImageVersion=${{ inputs.image-tag }}"
        if [[ "${{ inputs.set-asset-url }}" != "" ]]; then
          overrides="$overrides,AssetURL=${{ steps.sync-cdn.outputs.asset-url }}"
        fi
        if [[ "${{ inputs.parameter-overrides }}" != "" ]]; then
          overrides="$overrides,${{ inputs.parameter-overrides }}"
        fi
        echo "OVERRIDES=$overrides" >> $GITHUB_ENV
    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: ${{ inputs.name }}
        template: ${{ inputs.cf-template }}
        parameter-overrides: ${{ env.OVERRIDES }}
        tags: "[{\"Key\": \"cdci\",\"Value\":\"github\"},${{ inputs.tags }}]"
        capabilities: CAPABILITY_NAMED_IAM
        no-fail-on-empty-changeset: "1"